/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotoraceRouteImport } from './routes/motorace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated.operators'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated.games'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedOperatorsOperatorIdRouteImport } from './routes/_authenticated.operators.$operatorId'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1MotoraceStateRouteImport } from './routes/api/public/v1/motorace.state'
import { Route as ApiPublicV1MotoraceSettleRouteImport } from './routes/api/public/v1/motorace.settle'
import { Route as ApiPublicV1MotoraceLaunchRouteImport } from './routes/api/public/v1/motorace.launch'
import { Route as ApiPublicV1MotoraceBetRouteImport } from './routes/api/public/v1/motorace.bet'

const MotoraceRoute = MotoraceRouteImport.update({
  id: '/motorace',
  path: '/motorace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperatorsOperatorIdRoute =
  AuthenticatedOperatorsOperatorIdRouteImport.update({
    id: '/$operatorId',
    path: '/$operatorId',
    getParentRoute: () => AuthenticatedOperatorsRoute,
  } as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MotoraceStateRoute =
  ApiPublicV1MotoraceStateRouteImport.update({
    id: '/api/public/v1/motorace/state',
    path: '/api/public/v1/motorace/state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MotoraceSettleRoute =
  ApiPublicV1MotoraceSettleRouteImport.update({
    id: '/api/public/v1/motorace/settle',
    path: '/api/public/v1/motorace/settle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MotoraceLaunchRoute =
  ApiPublicV1MotoraceLaunchRouteImport.update({
    id: '/api/public/v1/motorace/launch',
    path: '/api/public/v1/motorace/launch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MotoraceBetRoute = ApiPublicV1MotoraceBetRouteImport.update({
  id: '/api/public/v1/motorace/bet',
  path: '/api/public/v1/motorace/bet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/motorace': typeof MotoraceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/operators': typeof AuthenticatedOperatorsRouteWithChildren
  '/operators/$operatorId': typeof AuthenticatedOperatorsOperatorIdRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/motorace/bet': typeof ApiPublicV1MotoraceBetRoute
  '/api/public/v1/motorace/launch': typeof ApiPublicV1MotoraceLaunchRoute
  '/api/public/v1/motorace/settle': typeof ApiPublicV1MotoraceSettleRoute
  '/api/public/v1/motorace/state': typeof ApiPublicV1MotoraceStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/motorace': typeof MotoraceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/operators': typeof AuthenticatedOperatorsRouteWithChildren
  '/operators/$operatorId': typeof AuthenticatedOperatorsOperatorIdRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/motorace/bet': typeof ApiPublicV1MotoraceBetRoute
  '/api/public/v1/motorace/launch': typeof ApiPublicV1MotoraceLaunchRoute
  '/api/public/v1/motorace/settle': typeof ApiPublicV1MotoraceSettleRoute
  '/api/public/v1/motorace/state': typeof ApiPublicV1MotoraceStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/motorace': typeof MotoraceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/operators': typeof AuthenticatedOperatorsRouteWithChildren
  '/_authenticated/operators/$operatorId': typeof AuthenticatedOperatorsOperatorIdRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/motorace/bet': typeof ApiPublicV1MotoraceBetRoute
  '/api/public/v1/motorace/launch': typeof ApiPublicV1MotoraceLaunchRoute
  '/api/public/v1/motorace/settle': typeof ApiPublicV1MotoraceSettleRoute
  '/api/public/v1/motorace/state': typeof ApiPublicV1MotoraceStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/motorace'
    | '/dashboard'
    | '/games'
    | '/operators'
    | '/operators/$operatorId'
    | '/api/public/v1/ping'
    | '/api/public/v1/motorace/bet'
    | '/api/public/v1/motorace/launch'
    | '/api/public/v1/motorace/settle'
    | '/api/public/v1/motorace/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/motorace'
    | '/dashboard'
    | '/games'
    | '/operators'
    | '/operators/$operatorId'
    | '/api/public/v1/ping'
    | '/api/public/v1/motorace/bet'
    | '/api/public/v1/motorace/launch'
    | '/api/public/v1/motorace/settle'
    | '/api/public/v1/motorace/state'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/motorace'
    | '/_authenticated/dashboard'
    | '/_authenticated/games'
    | '/_authenticated/operators'
    | '/_authenticated/operators/$operatorId'
    | '/api/public/v1/ping'
    | '/api/public/v1/motorace/bet'
    | '/api/public/v1/motorace/launch'
    | '/api/public/v1/motorace/settle'
    | '/api/public/v1/motorace/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  MotoraceRoute: typeof MotoraceRoute
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
  ApiPublicV1MotoraceBetRoute: typeof ApiPublicV1MotoraceBetRoute
  ApiPublicV1MotoraceLaunchRoute: typeof ApiPublicV1MotoraceLaunchRoute
  ApiPublicV1MotoraceSettleRoute: typeof ApiPublicV1MotoraceSettleRoute
  ApiPublicV1MotoraceStateRoute: typeof ApiPublicV1MotoraceStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motorace': {
      id: '/motorace'
      path: '/motorace'
      fullPath: '/motorace'
      preLoaderRoute: typeof MotoraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operators': {
      id: '/_authenticated/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operators/$operatorId': {
      id: '/_authenticated/operators/$operatorId'
      path: '/$operatorId'
      fullPath: '/operators/$operatorId'
      preLoaderRoute: typeof AuthenticatedOperatorsOperatorIdRouteImport
      parentRoute: typeof AuthenticatedOperatorsRoute
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/motorace/state': {
      id: '/api/public/v1/motorace/state'
      path: '/api/public/v1/motorace/state'
      fullPath: '/api/public/v1/motorace/state'
      preLoaderRoute: typeof ApiPublicV1MotoraceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/motorace/settle': {
      id: '/api/public/v1/motorace/settle'
      path: '/api/public/v1/motorace/settle'
      fullPath: '/api/public/v1/motorace/settle'
      preLoaderRoute: typeof ApiPublicV1MotoraceSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/motorace/launch': {
      id: '/api/public/v1/motorace/launch'
      path: '/api/public/v1/motorace/launch'
      fullPath: '/api/public/v1/motorace/launch'
      preLoaderRoute: typeof ApiPublicV1MotoraceLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/motorace/bet': {
      id: '/api/public/v1/motorace/bet'
      path: '/api/public/v1/motorace/bet'
      fullPath: '/api/public/v1/motorace/bet'
      preLoaderRoute: typeof ApiPublicV1MotoraceBetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOperatorsRouteChildren {
  AuthenticatedOperatorsOperatorIdRoute: typeof AuthenticatedOperatorsOperatorIdRoute
}

const AuthenticatedOperatorsRouteChildren: AuthenticatedOperatorsRouteChildren =
  {
    AuthenticatedOperatorsOperatorIdRoute:
      AuthenticatedOperatorsOperatorIdRoute,
  }

const AuthenticatedOperatorsRouteWithChildren =
  AuthenticatedOperatorsRoute._addFileChildren(
    AuthenticatedOperatorsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  MotoraceRoute: MotoraceRoute,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
  ApiPublicV1MotoraceBetRoute: ApiPublicV1MotoraceBetRoute,
  ApiPublicV1MotoraceLaunchRoute: ApiPublicV1MotoraceLaunchRoute,
  ApiPublicV1MotoraceSettleRoute: ApiPublicV1MotoraceSettleRoute,
  ApiPublicV1MotoraceStateRoute: ApiPublicV1MotoraceStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
